### ISSUE TITLE
Processor: ValueError: No JSON object could be loaded"

### ISSUE THREAD

**Issue by boredland** [DIYBookScanner/spreads#156]
When submitting the data from the scanners web-interface to the processor (started in mode "processor") I get the error "No JSON object could be loaded".
Here's the log of the scanners web-interface:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", line 327, in view_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", line 676, in submit_workflow
    data = json.loads(request.data)
  File "/usr/lib/python2.7/dist-packages/flask/json.py", line 149, in loads
    return _json.loads(s, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

while on the processors log this could be read:

```
spreadsplug.web.discovery	Contact from scanner 192.168.0.113, acknowledging.11:43:28
```

Perhaps this is caused by me running the processor in a Ubuntu 14.04 virtual machine. I'll give it a try in a live environment in the next days.

**Comment by jbaiter** [comment]
Could you take a look at the network transfer in your web browser (F12 in Firefox, Ctrl+J in Chrome) and check what the request to `/api/workflow/<id>/submit' looks like?
Also, a glance at the JavaScript panel to check for possible errors/warnings would be great, too :-)

**Comment by boredland** [comment]
Hi there,

this is the output from the console:

```
 bind(): You are binding a component method to the component. React does this for you automatically in a high-performance way, so you can safely remove this call. See SubmissionForm
http://192.168.0.113:5000/api/workflow/bc2bb7f1-6e33-4ca9-999d-880787c59a63/submit Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
```

**Comment by jbaiter** [comment]
OK, that is to be expected, nothing surprising there.
Did you manage to see the request?

**Comment by boredland** [comment]
How can I do that? By the way: installed spreads on a "real" machine for processing now, so nothing related to using VMware.

**Comment by boredland** [comment]
Got it:

```
message: "No JSON object could be decoded"
traceback: [,…]
0: "  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request↵    rv = self.dispatch_request()↵"
1: "  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request↵    return self.view_functions[rule.endpoint](**req.view_args)↵"
2: "  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", line 327, in view_func↵    return func(*args, **kwargs)↵"
3: "  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", line 676, in submit_workflow↵    data = json.loads(request.data)↵"
4: "  File "/usr/lib/python2.7/dist-packages/flask/json.py", line 149, in loads↵    return _json.loads(s, **kwargs)↵"
5: "  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads↵    return cls(encoding=encoding, **kw).decode(s)↵"
6: "  File "/usr/lib/python2.7/json/decoder.py", line 365, in decode↵    obj, end = self.raw_decode(s, idx=_w(s, 0).end())↵"
7: "  File "/usr/lib/python2.7/json/decoder.py", line 383, in raw_decode↵    raise ValueError("No JSON object could be decoded")↵"
type: "ValueError"
```

**Comment by jbaiter** [comment]
Try to submit a workflow while the "developer" pane/window is open (F12 in Firefox, Ctrl+J in Chrome), open the network tab in it, look for the request to "/api/workflow/<id>/submit", see what data is submitted.

**Comment by boredland** [comment]
(it's Ctrl+Shift+J)
Headers:
```
Remote Address:192.168.0.113:5000
Request URL:http://192.168.0.113:5000/api/workflow/bc2bb7f1-6e33-4ca9-999d-880787c59a63/submit
Request Method:POST
Status Code:500 INTERNAL SERVER ERROR
Request Headersview source
Accept:*/*
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8,de;q=0.6
Connection:keep-alive
Content-Length:808
Content-Type:application/json; charset=UTF-8
DNT:1
Host:192.168.0.113:5000
Origin:http://192.168.0.113:5000
Referer:http://192.168.0.113:5000/workflow/geschichte-des-todes/submit
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36
X-Requested-With:XMLHttpRequest
Request Payload
config%5Bdevice%5D%5Bchdkptp_path%5D=%2Fusr%2Flib%2Fchdkptp&config%5Bdevice%5D%5Bdpi%5D=300&config%5Bdevice%5D%5Bflip_target_pages%5D=false&config%5Bdevice%5D%5Bfocus_distance%5D=0&config%5Bdevice%5D%5Bfocus_mode%5D=autofocus_all&config%5Bdevice%5D%5Bmonochrome%5D=false&config%5Bdevice%5D%5Bparallel_capture%5D=true&config%5Bdevice%5D%5Bsensitivity%5D=80&config%5Bdevice%5D%5Bshoot_raw%5D=false&config%5Bdevice%5D%5Bshutter_speed%5D=1%2F25&config%5Bdevice%5D%5Bupside_down%5D=false&config%5Bdevice%5D%5Bwhitebalance%5D=Auto&config%5Bdevice%5D%5Bzoom_level%5D=3&config%5Bplugins%5D%5B%5D=hidtrigger&config%5Bplugins%5D%5B%5D=autorotate&config%5Bplugins%5D%5B%5D=scantailor&config%5Bplugins%5D%5B%5D=tesseract&config%5Bplugins%5D%5B%5D=pdfbeads&start_process=true&start_output=true&server=192.168.0.104%3A5000
Response Headersview source
Content-Length:1172
Content-Type:application/json
Server:TornadoServer/4.0.2
```
Preview:
```
message: "No JSON object could be decoded"
traceback: [,…]
0: "  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request↵    rv = self.dispatch_request()↵"
1: "  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request↵    return self.view_functions[rule.endpoint](**req.view_args)↵"
2: "  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", line 327, in view_func↵    return func(*args, **kwargs)↵"
3: "  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", line 676, in submit_workflow↵    data = json.loads(request.data)↵"
4: "  File "/usr/lib/python2.7/dist-packages/flask/json.py", line 149, in loads↵    return _json.loads(s, **kwargs)↵"
5: "  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads↵    return cls(encoding=encoding, **kw).decode(s)↵"
6: "  File "/usr/lib/python2.7/json/decoder.py", line 365, in decode↵    obj, end = self.raw_decode(s, idx=_w(s, 0).end())↵"
7: "  File "/usr/lib/python2.7/json/decoder.py", line 383, in raw_decode↵    raise ValueError("No JSON object could be decoded")↵"
type: "ValueError"
```

**Comment by jbaiter** [comment]
Thanks, I think I have a suspicion as to what is happening, unfortunately I won't be able to inspect it further before next week :/
