### ISSUE TITLE
Web plugin activation fail

### ISSUE THREAD

**Issue by Cypris201** [DIYBookScanner/spreads#159]
Hi, I've got a problem to activate the web plugin during configure process. I can activate all the other plugins, but wenn activate the web plugin the configuration crashes with the error:

```
Select a plugin (or hit enter to finish): 
/usr/lib/python2.7/dist-packages/jpegtran/__pycache__/_cffi__xe4b52a61x1d19a8ef.c:186:18: fatal error: Epeg.h: Datei oder Verzeichnis nicht gefunden
 #include "Epeg.h"
                  ^
compilation terminated.
spreads encountered an error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spreads/main.py", line 227, in main
    run()
  File "/usr/lib/python2.7/dist-packages/spreads/main.py", line 220, in run
    args.subcommand(config)
  File "/usr/lib/python2.7/dist-packages/spreads/cli.py", line 173, in configure
    _setup_processing_pipeline(config)
  File "/usr/lib/python2.7/dist-packages/spreads/cli.py", line 118, in _setup_processing_pipeline
    exts = [name for name, cls in plugin.get_plugins(*config["plugins"].get())
  File "/usr/lib/python2.7/dist-packages/spreads/plugin.py", line 364, in get_plugins
    plugin = ext.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/spreadsplug/web/__init__.py", line 38, in <module>
    import web
  File "/usr/lib/python2.7/dist-packages/spreadsplug/web/web.py", line 30, in <module>
    from util import (WorkflowConverter, get_thumbnail, scale_image, convert_image,
  File "/usr/lib/python2.7/dist-packages/spreadsplug/web/util.py", line 38, in <module>
    from jpegtran import JPEGImage
  File "/usr/lib/python2.7/dist-packages/jpegtran/__init__.py", line 1, in <module>
    from jpegtran.transform import JPEGImage
  File "/usr/lib/python2.7/dist-packages/jpegtran/transform.py", line 5, in <module>
    import jpegtran.lib as lib
  File "/usr/lib/python2.7/dist-packages/jpegtran/lib.py", line 36, in <module>
    libraries=["jpeg"])
  File "/usr/lib/python2.7/dist-packages/cffi/api.py", line 340, in verify
    lib = self.verifier.load_library()
  File "/usr/lib/python2.7/dist-packages/cffi/verifier.py", line 74, in load_library
    self._compile_module()
  File "/usr/lib/python2.7/dist-packages/cffi/verifier.py", line 139, in _compile_module
    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
  File "/usr/lib/python2.7/dist-packages/cffi/ffiplatform.py", line 25, in compile
    outputfilename = _build(tmpdir, ext)
  File "/usr/lib/python2.7/dist-packages/cffi/ffiplatform.py", line 51, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
VerificationError: CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

```
Can anybody explain me what I am missing. Oh and my OS ist Lubuntu 14.01 I think.

**Comment by knjigor** [comment]
Hi, on what os did you installed it? Was it a fresh install or not?

**Comment by Cypris201** [comment]
Yes it was a fresh install

**Comment by knjigor** [comment]
I`m using lubuntu 14.04 LTS on MSI Wind U160 (preaty low performances) as server for taking images (scanning) and I`m using only Web plugin for that. What install tutorial did you use, trie with this one https://github.com/OliPelz/spreads-ubuntu-trusty for me it is working out of the box (there is a step about downgradeing web plugin to older version because of some bug (not shure what it is)).

**Comment by Cypris201** [comment]
Ok this didn't work for me, but I run your guide over my exiting installation. I'll try it tomorrow with a fresh one. Thanks

**Comment by Cypris201** [comment]
Ok, now it's working.

**Comment by jbaiter** [comment]
JFYI, the downgrade is *not* neccessary, the "bug" was merely a failure to compile the JavaScript bundles, which can easily be resolved by installing the pre-compiled packages from http://buildbot.diybookscanner.org.
Sorry for not keeping the Debian packages up-to-date :/

**Comment by Cypris201** [comment]
You can close this Issue.
