### ISSUE TITLE
Missing images in web

### ISSUE THREAD

**Issue by knjigor** [DIYBookScanner/spreads#163]
Hi, I have founded a strange behavior in spreads web. When for some reason there is loosing of connection with cameras and server and after what I reset spread web and reconnect cameras and continue to work, I'm facing missing pictures, yesterday about 100 of them in a row. Looking at terminal (verbose output) every thing looks ok, looking at raw folder with pictures they are there but when I go to browser pages are missing when I click on workflow. When I start with capturing cropping areas are sometimes moved but still right sized, cameras are working as expected pictures are taken, cropped and saved to right raw folder, but spreads aren't registering them. The connection lost error is this:

````
CHDKCameraDevice[96C0]: Error during capture, retrying shot.
chdkptp.lua: rc chunk get 1 0
chdkptp.lua: rc chunk size:10240 offset:nil last:false
chdkptp.lua: rc chunk get 1 1
chdkptp.lua: rc chunk size:4561004 offset:nil last:true
CHDKCameraDevice[E852]: Setting EXIF orientation on captured image
spreadsplug.web: {'msg': 'no matching device', 'etype': 'connect_no_dev', 'trace                                                                                               back': '\nstack traceback:\n\t[C]: in function \'connect\'\n\t...on2.7/site-pack                                                                                               ages/chdkptp/vendor/chdkptp/lua/chdku.lua:1510: in function \'connect\'\n\t...on                                                                                               2.7/site-packages/chdkptp/vendor/chdkptp/lua/chdku.lua:1537: in function <...on2                                                                                               .7/site-packages/chdkptp/vendor/chdkptp/lua/chdku.lua:1525>\n\t[C]: in function                                                                                                \'pcall\'\n\t[string "<python>"]:1: in function <[string "<python>"]:1>'}
Traceback (most recent call last):
  File "/home/bsu/.spreads/local/lib/python2.7/site-packages/flask/app.py", line                                                                                                1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bsu/.spreads/local/lib/python2.7/site-packages/flask/app.py", line                                                                                                1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bsu/.spreads/local/lib/python2.7/site-packages/spreadsplug/web/end                                                                                               points.py", line 327, in view_func
    return func(*args, **kwargs)
  File "/home/bsu/.spreads/local/lib/python2.7/site-packages/spreadsplug/web/end                                                                                               points.py", line 951, in trigger_capture
    workflow.capture(retake=('retake' in request.args))
  File "/home/bsu/.spreads/local/lib/python2.7/site-packages/spreads/workflow.py                                                                                               ", line 104, in wrapped_func
    func(*args, **kwargs)
  File "/home/bsu/.spreads/local/lib/python2.7/site-packages/spreads/workflow.py                                                                                               ", line 913, in capture
    util.check_futures_exceptions(futures)
  File "/home/bsu/.spreads/local/lib/python2.7/site-packages/spreads/util.py", l                                                                                               ine 119, in check_futures_exceptions
    raise next(x for x in futures if x.exception()).exception()
LuaError: {'msg': 'no matching device', 'etype': 'connect_no_dev', 'traceback':                                                                                                '\nstack traceback:\n\t[C]: in function \'connect\'\n\t...on2.7/site-packages/ch                                                                                               dkptp/vendor/chdkptp/lua/chdku.lua:1510: in function \'connect\'\n\t...on2.7/sit                                                                                               e-packages/chdkptp/vendor/chdkptp/lua/chdku.lua:1537: in function <...on2.7/site                                                                                               -packages/chdkptp/vendor/chdkptp/lua/chdku.lua:1525>\n\t[C]: in function \'pcall                                                                                               \'\n\t[string "<python>"]:1: in function <[string "<python>"]:1>'}
tornado.access: 500 POST /api/workflow/3dd64a9f-6a7a-4c0a-ade6-522e1813837c/capt                                                                                               ure (192.168.129.89) 4343.48ms
^Chuey.consumer.ConsumerThread: Shutdown initiated
attempted to close non-present device 001:005
ERROR: Could not close session!
```   

And one more thing, while in capturing mode thumbnail pictures and cropping pictures are prewievd correctly.

**Comment by knjigor** [comment]
This is one more error that is rising:

```
Workflow: Triggering capture.
Workflow: Sending capture command to devices
chdkptp.lua: rc chunk get 1 0
chdkptp.lua: rc chunk size:10240 offset:nil last:false
chdkptp.lua: rc chunk get 1 0
chdkptp.lua: rc chunk get 1 1
unexpected packet type 0x0
chdkptp.lua: rc chunk size:4993053 offset:nil last:true
CHDKCameraDevice[96C0]: Setting EXIF orientation on captured image
CHDKCameraDevice[E852]: Error during capture, retrying shot.
ERROR: Could not close session!
chdkptp.lua: rc chunk get 1 0
chdkptp.lua: rc chunk size:4672034 offset:nil last:true
CHDKCameraDevice[E852]: Setting EXIF orientation on captured image
spreadsplug.web: Could not find EXIF data
Traceback (most recent call last):
  File "/home/bsu/.spreads/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bsu/.spreads/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bsu/.spreads/local/lib/python2.7/site-packages/spreadsplug/web/endpoints.py", line 327, in view_func
    return func(*args, **kwargs)
  File "/home/bsu/.spreads/local/lib/python2.7/site-packages/spreadsplug/web/endpoints.py", line 951, in trigger_capture
    workflow.capture(retake=('retake' in request.args))
  File "/home/bsu/.spreads/local/lib/python2.7/site-packages/spreads/workflow.py", line 104, in wrapped_func
    func(*args, **kwargs)
  File "/home/bsu/.spreads/local/lib/python2.7/site-packages/spreads/workflow.py", line 913, in capture
    util.check_futures_exceptions(futures)
  File "/home/bsu/.spreads/local/lib/python2.7/site-packages/spreads/util.py", line 119, in check_futures_exceptions
    raise next(x for x in futures if x.exception()).exception()
NoExifDataFound: Could not find EXIF data
tornado.access: 500 POST /api/workflow/02b97fa2-2aac-4929-9015-5601b8cb9c4d/capture (192.168.129.89) 24117.83ms
```

**Comment by jbaiter** [comment]
First of all, *never ever ever* reset your Pi while a capture is ongoing, *always* hit "finish capture" and wait until you're back at the list screen before you do anything.
Second, *never ever ever* reset your Pi by just plugging it out, use the "Shutdown" menu from the web interface or SSH onto the machine and properly shut it down from there.
Third, if you quit spreads while a workflow is in progress, some pictures will not be registered in the Workflow `pages.json` file, which is only written after you've finished a capture. If I remember correctly, I decided to do this because of performance issues, but I've just reverted that decision, please let me know if it works again and if you've noticed any performance degradation.

**Comment by jbaiter** [comment]
For the other thing, please open a separate issue.

**Comment by knjigor** [comment]
```...never ever ever reset your Pi``` 
Unfortunately that was just the thing i was doing, expect i'm not using  Pi, i'm using small netbook with lubuntu and spreads installed, but i was shutting down spreads when connection to cameras was lost or something stopped working. : (

I have updated my system and tested it and so far it is working good, performances with my book scann unit are about 1286-1360 pages per hour and with commit 1a433f8 it stays in that range.
