### ISSUE TITLE
PTPError: I/O error (ptp_code: 767),

### ISSUE THREAD

**Issue by boredland** [DIYBookScanner/spreads#173]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", line 327, in view_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", line 929, in prepare_capture
    workflow.prepare_capture()
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 858, in prepare_capture
    if any(dev.target_page is None for dev in self.devices):
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 511, in devices
    self._devices = plugin.get_devices(self.config, force_reload=True)
  File "/usr/local/lib/python2.7/dist-packages/spreads/plugin.py", line 480, in get_devices
    devices = list(driver.yield_devices(config['device']))
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/dev/chdkcamera.py", line 108, in yield_devices
    yield SPECIAL_CASES[ids](config, chdkptp.ChdkDevice(info))
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/dev/chdkcamera.py", line 130, in __init__
    self._zoom_steps = self._device.lua_execute("return get_zoom_steps()")
  File "/usr/local/lib/python2.7/dist-packages/chdkptp/device.py", line 184, in lua_execute
    """ % (lua_code, remote_libs)).values()
  File "/usr/local/lib/python2.7/dist-packages/chdkptp/lua.py", line 71, in pexecute
    return self._parse_rval(self._rt.execute(checked_code))
  File "/usr/local/lib/python2.7/dist-packages/chdkptp/lua.py", line 39, in _parse_rval
    self._raise_exception(rval)
  File "/usr/local/lib/python2.7/dist-packages/chdkptp/lua.py", line 29, in _raise_exception
    raise PTPError(errval)
PTPError: I/O error (ptp_code: 767)

```
In latest SpreadPi image, cant reproduce when it occurs. Sometimes it doesn't.

**Comment by jbaiter** [comment]
Did you manage to resolve the issue? Was it hardware or CHDK-related?

**Comment by boredland** [comment]
No, but I saw that it was already issued.

2015-03-03 19:10 GMT+01:00 Johannes Baiter <notifications@github.com>:
