### ISSUE TITLE
"Bad CRC-32 for file"

### ISSUE THREAD

**Issue by boredland** [DIYBookScanner/spreads#174]
Whenever I try to submit a file from a spreadpi-powered scanning-device to a device running in processor mode, I get this. Everytime the name of the jpeg varies 000.jpg, 003.jpg (There are only four shots in..).
```
tornado.application: Uncaught exception POST /api/workflow/upload (192.168.0.113)
HTTPServerRequest(protocol='http', host='192.168.0.202:5000', method='POST', uri='/api/workflow/upload', version='HTTP/1.1', remote_ip='192.168.0.113', headers={'Content-Length': '9543711', 'Accept-Encoding': 'gzip, deflate', 'Content-Type': 'application/zip', 'Host': '192.168.0.202:5000', 'Accept': '*/*', 'User-Agent': 'python-requests/2.3.0 CPython/2.7.3 Linux/3.18.7+'})
Traceback (most recent call last):
  File "/home/firefly/.spreads/local/lib/python2.7/site-packages/tornado/web.py", line 1346, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/firefly/spreads-deploy/spreads-0.5git20150226.924b/spreadsplug/web/handlers.py", line 170, in post
    zf.extractall(path=self.base_path)
  File "/usr/lib/python2.7/zipfile.py", line 1040, in extractall
    self.extract(zipinfo, path, pwd)
  File "/usr/lib/python2.7/zipfile.py", line 1028, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/lib/python2.7/zipfile.py", line 1084, in _extract_member
    shutil.copyfileobj(source, target)
  File "/usr/lib/python2.7/shutil.py", line 49, in copyfileobj
    buf = fsrc.read(length)
  File "/usr/lib/python2.7/zipfile.py", line 632, in read
    data = self.read1(n - len(buf))
  File "/usr/lib/python2.7/zipfile.py", line 672, in read1
    self._update_crc(data, eof=(self._compress_left==0))
  File "/usr/lib/python2.7/zipfile.py", line 647, in _update_crc
    raise BadZipfile("Bad CRC-32 for file %r" % self.name)
BadZipfile: Bad CRC-32 for file 'test1234/data/raw/000.jpg'
tornado.access: 500 POST /api/workflow/upload (192.168.0.113) 2753.19ms
```

**Comment by boredland** [comment]
I tried this on a different machine: same error. I updated the spreadpi-image: same error.

**Comment by boredland** [comment]
I checked the files, they display perfectly after upload. So, at least no obvious, errors during transfer.

**Comment by jbaiter** [comment]
So the upload does work, it's just that it throws an exception after it is done?

**Comment by boredland** [comment]
Jep. And after that no post-processing.

2015-03-26 14:29 GMT+01:00 Johannes Baiter <notifications@github.com>:

**Comment by boredland** [comment]
Can't reproduce this anymore.
