### ISSUE TITLE
Could not open HID device - Udev applied.

### ISSUE THREAD

**Issue by boredland** [DIYBookScanner/spreads#176]
I know this being an old issue, but even though I created the udev-rule exactly like for the raspberry-image (https://github.com/DIYBookScanner/spreadpi/blob/master/delivery/scripts/05-udev.sh) I get the following error. Any ideas?
```
(.spreads)firefly@firefly:~$ spread web --debug
spreadsplug.web: Starting scanning station server in "full" mode
spreadsplug.web: Starting server in debugging mode
huey.consumer.ConsumerThread: 1 worker threads
huey.consumer.ConsumerThread: Setting signal handler
huey.consumer.ConsumerThread: Huey consumer initialized with following commands
+ process_workflow
+ upload_workflow
+ transfer_to_stick
+ output_workflow
huey.consumer.ConsumerThread: Starting scheduler thread
huey.consumer.ConsumerThread: Starting worker threads
huey.consumer.ConsumerThread: Starting periodic task scheduler thread
spreadsplug.web.discovery: Starting discovery listener
root: Cache missed, instantiating workflow from /home/firefly/scans/rest.
Workflow: Initializing workflow /home/firefly/scans/rest
root: Adding setting shutter_speed from device
root: Adding setting upside_down from device
root: Adding setting flip_target_pages from device
root: Adding setting focus_distance from device
root: Adding setting sensitivity from device
root: Adding setting shoot_raw from device
root: Adding setting zoom_level from device
root: Adding setting parallel_capture from device
root: Adding setting monochrome from device
root: Adding setting focus_mode from device
root: Adding setting whitebalance from device
root: Adding setting dpi from device
root: Adding setting loglevel from core
root: Adding setting capture_keys from core
root: Adding setting logfile from core
root: Adding setting verbose from core
root: Adding setting content from scantailor
root: Adding setting detection from scantailor
root: Adding setting rotate from scantailor
root: Adding setting deskew from scantailor
root: Adding setting split_pages from scantailor
root: Adding setting autopilot from scantailor
root: Adding setting auto_margins from scantailor
root: Adding setting margins from scantailor
root: Adding setting language from tesseract
root: Adding setting mode from web
root: Adding setting standalone_device from web
root: Adding setting debug from web
root: Adding setting postprocessing_server from web
root: Adding setting project_dir from web
root: Adding setting port from web
spreadsplug.hidtrigger: Initializing HidTrigger plugin
spreadsplug.web: Could not open HID device, please check your permissions on /dev/bus/usb.
Traceback (most recent call last):
  File "/home/firefly/.spreads/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/firefly/.spreads/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/firefly/spreads-deploy/spreads-0.5git20150226.924b/spreadsplug/web/endpoints.py", line 522, in list_workflows
    workflows = Workflow.find_all(app.config['base_path'])
  File "/home/firefly/spreads-deploy/spreads-0.5git20150226.924b/spreads/workflow.py", line 355, in find_all
    workflow = cls(candidate)
  File "/home/firefly/spreads-deploy/spreads-0.5git20150226.924b/spreads/workflow.py", line 466, in __init__
    self._plugins = [cls(self.config) for name, cls in plugin_classes]
  File "/home/firefly/spreads-deploy/spreads-0.5git20150226.924b/spreadsplug/hidtrigger.py", line 46, in __init__
    for dev in self._find_devices():
  File "/home/firefly/spreads-deploy/spreads-0.5git20150226.924b/spreadsplug/hidtrigger.py", line 112, in _find_devices
    raise DeviceException("Could not open HID device, please check"
DeviceException: Could not open HID device, please check your permissions on /dev/bus/usb.
```

**Comment by jbaiter** [comment]
Only the first error is hidtrigger-related.
What does `ls -l /dev/bus/usb/*` tell you?

**Comment by boredland** [comment]
```
ls -l /dev/bus/usb/*
/dev/bus/usb/001:
total 0
crw-rw-r-- 1 root root 189, 0 Jan  1  2011 001

/dev/bus/usb/002:
total 0
crw-rw-r-- 1 root root 189, 128 Jan  1  2011 001

/dev/bus/usb/003:
total 0
crw-rw-r-- 1 root root 189, 256 Jan  1  2011 001
crw-rw-r-- 1 root root 189, 257 Jan  1  2011 002
```

**Comment by jbaiter** [comment]
Well, this means either your udev rule is wrong or it's not applied for some reason.
Those devices are only writable by root.
Did you restart udev after adding the rule?

**Comment by boredland** [comment]
I think, perhaps, this gets overwritten by a static entry in initramfs. I'll check that later. 
Nevertheless: the hidtrigger-plugin gets called even though it is not activated. That isn't right I think?

**Comment by jbaiter** [comment]
That's not right, yeah. "Not activated" means no "hidtrigger" entry under the "plugins" entry in the configuration, right?

**Comment by boredland** [comment]
Yes.

**Comment by boredland** [comment]
I think this is/was virtualenv-related. Without those problems disappear.

**Comment by boredland** [comment]
Well for the device again where it should be active:
005 is my pedal, 8 and 9 are my cameras.
```
crw-rw-r-- 1 root root    189, 260 Mar  4 11:55 005
crw-rw-r-- 1 root plugdev 189, 263 Mar  4 11:55 008
crw-rw-r-- 1 root plugdev 189, 264 Mar  4 11:56 009
```
I added my current user to plugdev and the cameras work:
```
sudo usermod -a -G plugdev $(whoami)
```
Now I need to figure out, why my hidtrigger is not served for the group plugdev...

**Comment by boredland** [comment]
Just to make that sure: adding permissions for the plugdev-group doesn't enable hid-triggerin. I guess I must have missed out something in the install of hidtrigger.
This it what I do for installing:
1. libhidapi-dev via aptitude
2. hidapi-cffi via pip
3. Install the hidtrigger egg from the latest built.
Did I miss something?

**Comment by boredland** [comment]
Can't reproduce this anymore.
