### ISSUE TITLE
LuaError

### ISSUE THREAD

**Issue by boredland** [DIYBookScanner/spreads#177]
After the current version of my install-script (https://github.com/boredland/spreads-deploy/blob/b090eafb9cbad8b9f268f9dbf3d16dc504ab8b8d/aio_install.sh) I get several errors with lupa when trying to communicate with the cameras (I tried to configure the target pages). I think this is connected with the recent change at the iup-install via the chdkptp.py. Can you confirm this?

```
spreads encountered an error:
Traceback (most recent call last):
  File "/home/firefly/spreads-deploy/spreads-0.5git20150226.924b/spreads/main.py", line 321, in main
    run()
  File "/home/firefly/spreads-deploy/spreads-0.5git20150226.924b/spreads/main.py", line 308, in run
    args.subcommand(config)
  File "/home/firefly/spreads-deploy/spreads-0.5git20150226.924b/spreads/cli.py", line 232, in configure
    _set_device_target_page(config, target_page)
  File "/home/firefly/spreads-deploy/spreads-0.5git20150226.924b/spreads/cli.py", line 177, in _set_device_target_page
    devs = plugin.get_devices(config, force_reload=True)
  File "/home/firefly/spreads-deploy/spreads-0.5git20150226.924b/spreads/plugin.py", line 480, in get_devices
    devices = list(driver.yield_devices(config['device']))
  File "/home/firefly/spreads-deploy/spreads-0.5git20150226.924b/spreadsplug/dev/chdkcamera.py", line 105, in yield_devices
    for info in chdkptp.list_devices():
  File "/home/firefly/.spreads/local/lib/python2.7/site-packages/chdkptp/device.py", line 51, in list_devices
    """)
  File "/home/firefly/.spreads/local/lib/python2.7/site-packages/chdkptp/lua.py", line 60, in execute
    return self._rt.execute(lua_code)
  File "lupa/_lupa.pyx", line 253, in lupa._lupa.LuaRuntime.execute (lupa/_lupa.c:4473)
  File "lupa/_lupa.pyx", line 1236, in lupa._lupa.run_lua (lupa/_lupa.c:17138)
  File "lupa/_lupa.pyx", line 1254, in lupa._lupa.execute_lua_call (lupa/_lupa.c:17400)
  File "lupa/_lupa.pyx", line 1207, in lupa._lupa.raise_lua_error (lupa/_lupa.c:16746)
LuaError
```

**Comment by boredland** [comment]
Can't reproduce this anymore.
