### ISSUE TITLE
Unhandled exception in worker-thread

### ISSUE THREAD

**Issue by boredland** [DIYBookScanner/spreads#178]
If no CRC-Errors I get this one: 
```
Traceback (most recent call last):
  File "/home/firefly/spreads-deploy/spreads-0.5git20150226.924b/spreads/vendor/huey/consumer.py", line 149, in process_task
    self.huey.execute(task)
  File "/home/firefly/spreads-deploy/spreads-0.5git20150226.924b/spreads/vendor/huey/api.py", line 236, in execute
    result = task.execute()
  File "/home/firefly/spreads-deploy/spreads-0.5git20150226.924b/spreads/vendor/huey/api.py", line 415, in execute
    return func(*args, **kwargs)
  File "/home/firefly/spreads-deploy/spreads-0.5git20150226.924b/spreadsplug/web/tasks.py", line 166, in process_workflow
    workflow.process()
  File "/home/firefly/spreads-deploy/spreads-0.5git20150226.924b/spreads/workflow.py", line 957, in process
    self._run_hook('process', self.pages, processed_path)
  File "/home/firefly/spreads-deploy/spreads-0.5git20150226.924b/spreads/workflow.py", line 818, in _run_hook
    getattr(plug, hook_name)(*args)
  File "/home/firefly/spreads-deploy/spreads-0.5git20150226.924b/spreadsplug/tesseract.py", line 110, in process
    self._perform_replacements(fname)
  File "/home/firefly/spreads-deploy/spreads-0.5git20150226.924b/spreadsplug/tesseract.py", line 193, in _perform_replacements
    content = fp.read()
  File "/home/firefly/.spreads/lib/python2.7/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2840: ordinal not in range(128)

```

**Comment by boredland** [comment]
Here a longer log so you can reproduce where it occurs:
```
Workflow: Starting postprocessing...
Workflow: Running 'process' hooks
spreadsplug.autorotate: Rotating images
spreadsplug.scantailor: Generating ScanTailor configuration
spreadsplug.scantailor: /usr/local/bin/scantailor-cli --start-filter=2 --end-filter=5 --layout=1.5 -o=/tmp/tmpYuy5FP.ScanTailor --margins-top=2.5 --margins-right=2.5 --margins-bottom=2.5 --margins-left=2.5 /home/firefly/scans/werer/data/done/004_rotated.jpg /home/firefly/scans/werer/data/done/005_rotated.jpg /home/firefly/scans/werer/data/done/006_rotated.jpg /home/firefly/scans/werer/data/done/007_rotated.jpg /tmp/st-outQFDY54
spreadsplug.scantailor: Generating output images from ScanTailor configuration.
spreadsplug.scantailor: Generating output...
spreadsplug.scantailor: Launching those subprocesses!
spreadsplug.tesseract: Performing OCR
spreadsplug.tesseract: Language is "deu"
spreadsplug.tesseract: [u'/usr/local/bin/tesseract', u'/home/firefly/scans/werer/data/done/006_rotated.tif', u'/tmp/tess-outYg86mW/006_rotated', u'-l', u'deu', u'hocr']
spreadsplug.tesseract: [u'/usr/local/bin/tesseract', u'/home/firefly/scans/werer/data/done/005_rotated.tif', u'/tmp/tess-outYg86mW/005_rotated', u'-l', u'deu', u'hocr']
spreadsplug.tesseract: [u'/usr/local/bin/tesseract', u'/home/firefly/scans/werer/data/done/007_rotated.tif', u'/tmp/tess-outYg86mW/007_rotated', u'-l', u'deu', u'hocr']
spreadsplug.tesseract: [u'/usr/local/bin/tesseract', u'/home/firefly/scans/werer/data/done/004_rotated.tif', u'/tmp/tess-outYg86mW/004_rotated', u'-l', u'deu', u'hocr']
huey.consumer.ConsumerThread: Unhandled exception in worker thread
Traceback (most recent call last):
  File "/home/firefly/.spreads/local/lib/python2.7/site-packages/spreads/vendor/huey/consumer.py", line 149, in process_task
    self.huey.execute(task)
  File "/home/firefly/.spreads/local/lib/python2.7/site-packages/spreads/vendor/huey/api.py", line 236, in execute
    result = task.execute()
  File "/home/firefly/.spreads/local/lib/python2.7/site-packages/spreads/vendor/huey/api.py", line 415, in execute
    return func(*args, **kwargs)
  File "/home/firefly/.spreads/local/lib/python2.7/site-packages/spreadsplug/web/tasks.py", line 166, in process_workflow
    workflow.process()
  File "/home/firefly/.spreads/local/lib/python2.7/site-packages/spreads/workflow.py", line 957, in process
    self._run_hook('process', self.pages, processed_path)
  File "/home/firefly/.spreads/local/lib/python2.7/site-packages/spreads/workflow.py", line 818, in _run_hook
    getattr(plug, hook_name)(*args)
  File "/home/firefly/.spreads/local/lib/python2.7/site-packages/spreadsplug/tesseract.py", line 110, in process
    self._perform_replacements(fname)
  File "/home/firefly/.spreads/local/lib/python2.7/site-packages/spreadsplug/tesseract.py", line 193, in _perform_replacements
    content = fp.read()
  File "/home/firefly/.spreads/lib/python2.7/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2532: ordinal not in range(128)
```
