### ISSUE TITLE
Tesseract OpenCl

### ISSUE THREAD

**Issue by boredland** [DIYBookScanner/spreads#182]
Invoking spreads with a Tesseract Version compiled with OpenCl fails, since the spreads command (tesseract --list-langs) creates the opencl-binary. Even though that is perhaps the fault of tesseract producing the kernel-files when they aren't needed:
Spreads isn't so happy about those files being put into the scans-folder:

```
root: Cache missed, instantiating workflow from /home/jonas/scans/kernel-Intel(R)_Xeon(R)_CPU___________X5650__@_2.67GHz.bin.
Workflow: Initializing workflow /home/jonas/scans/kernel-Intel(R)_Xeon(R)_CPU___________X5650__@_2.67GHz.bin
spreadsplug.web: [Errno 20] Not a directory: '/home/jonas/scans/kernel-Intel(R)_Xeon(R)_CPU___________X5650__@_2.67GHz.bin'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", line 522, in list_workflows
    workflows = Workflow.find_all(app.config['base_path'])
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 355, in find_all
    workflow = cls(candidate)
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 426, in __init__
    self.bag = bagit.Bag(unicode(self.path))
  File "/usr/local/lib/python2.7/dist-packages/spreads/vendor/bagit.py", line 111, in __init__
    self._init_bag()
  File "/usr/local/lib/python2.7/dist-packages/spreads/vendor/bagit.py", line 275, in _init_bag
    if os.listdir(self.path):
OSError: [Errno 20] Not a directory: '/home/jonas/scans/kernel-Intel(R)_Xeon(R)_CPU___________X5650__@_2.67GHz.bin'
tornado.access: 500 GET /api/workflow (127.0.0.1) 3.84ms
```

**Comment by jbaiter** [comment]
Oh wow, that is cleary not ideal from tesseract's side... I'll see if I can work around that, should be possible by overriding the current working directly when listing the languages.

**Comment by boredland** [comment]
I'll file a report at tesseract to fix that. For "--list-langs" there'sn
absolutely no need for the binarys to be created. In fact a much better
way, when the binarys are needed, would be to create those im tmp-folders
or something. Like that, when a tesseract-job is finished, those binarys
remain in the working-directory wich clearly is unnecessary...

2015-03-26 14:30 GMT+01:00 Johannes Baiter <notifications@github.com>:

**Comment by boredland** [comment]
Closing this myself as the reporter — I'm no longer pursuing it, and I'd rather not leave it sitting in your triage queue.

No action is needed from the maintainers, and this says nothing about the validity of the report: if anyone else is hitting the same thing, please reopen or file fresh.

**Comment by boredland** [comment]
Reopening — please disregard my previous comment.

That closure was a mistake on my side: it came from a bulk sweep of my own filed issues, not from a considered decision to withdraw this report. Sorry for the noise in your notifications.

The report stands as originally written.
