### ISSUE TITLE
AttributeError coming from util.py on Ubuntu

### ISSUE THREAD

**Issue by Zev-Chonoles** [DIYBookScanner/spreads#188]
I'm trying to use spreads on an Ubuntu 14.04 desktop. I've installed all the dependencies that I saw mentioned, and I was able to run `spread configure` just fine, but whenever I run spreads and get to the point where I'd start capturing, I get an error `AttributeError: 'str' object has no attribute 'msg'`

More specifically, when I start the GUI and have chosen all my settings, I click 'Next' and see
```
zev@zev-X58A-UD7:~$ spread gui
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/gui/gui.py", line 235, in validatePage
    wizard.workflow.prepare_capture()
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 880, in prepare_capture
    util.check_futures_exceptions(futures)
  File "/usr/local/lib/python2.7/dist-packages/spreads/util.py", line 119, in check_futures_exceptions
    raise next(x for x in futures if x.exception()).exception()
AttributeError: 'str' object has no attribute 'msg'
```
When running the CLI wizard, here's how it manifests:
```
zev@zev-X58A-UD7:~$ spread wizard ~/spread-test
==========================
 Starting capturing process
 ==========================
Found 2 devices!
Setting up devices for capturing.
spreads encountered an error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line 321, in main
    run()
  File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line 308, in run
    args.subcommand(config)
  File "/usr/local/lib/python2.7/dist-packages/spreads/cli.py", line 388, in wizard
    capture(config)
  File "/usr/local/lib/python2.7/dist-packages/spreads/cli.py", line 335, in capture
    workflow.prepare_capture()
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 880, in prepare_capture
    util.check_futures_exceptions(futures)
  File "/usr/local/lib/python2.7/dist-packages/spreads/util.py", line 119, in check_futures_exceptions
    raise next(x for x in futures if x.exception()).exception()
AttributeError: 'str' object has no attribute 'msg'
```
Any advice? I'm happy to provide any more information that might help diagnose the problem.

**Comment by jbaiter** [comment]
That looks like an interesting one!

- Can you please run with `spread --verbose wizard ~/spread-test` and upload the log somewhere? This will give me more to go on.
- What driver are you using?

**Comment by Zev-Chonoles** [comment]
Sorry for taking so long to reply. I'm using two Canon A2500 cameras with CHDK driver `a2500-100a-1.3.0-4132-full_ALPHA` (I suppose the fact that it's an alpha version doesn't bode well).

Here's the output from the CLI using the `--verbose` flag:

```
zev@zev-X58A-UD7:~$ spread --verbose wizard spread-test
==========================
 Starting capturing process
 ==========================
Workflow: Initializing workflow spread-test
bagit: Adding path /home/zev/spread-test/bag-info.txt to payload
bagit: Adding path spread-test/config.yml to payload
spreads.plugin: Finding devices for driver "CHDKCameraDevice"
Found 2 devices!
Setting up devices for capturing.
Workflow: Preparing capture.
Workflow: Preparing capture in devices
spreads encountered an error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line 321, in main
    run()
  File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line 308, in run
    args.subcommand(config)
  File "/usr/local/lib/python2.7/dist-packages/spreads/cli.py", line 388, in wizard
    capture(config)
  File "/usr/local/lib/python2.7/dist-packages/spreads/cli.py", line 335, in capture
    workflow.prepare_capture()
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 880, in prepare_capture
    util.check_futures_exceptions(futures)
  File "/usr/local/lib/python2.7/dist-packages/spreads/util.py", line 119, in check_futures_exceptions
    raise next(x for x in futures if x.exception()).exception()
AttributeError: 'str' object has no attribute 'msg'
```

Please let me know if there's anything else I can provide.

**Comment by markvdb** [comment]
Johannes,

Maybe it would make sense to add a very sturdy get_version() to the debug
output so it would at least attempt to discover the exact camera and CHDK
version?

Mark

2015-05-04 9:47 GMT+02:00 Zev Chonoles <notifications@github.com>:

> Sorry for taking so long to reply. I'm using two Canon A2500 cameras with
> CHDK driver a2500-100a-1.3.0-4132-full_ALPHA (I suppose the fact that
> it's an alpha version doesn't bode well).
>
> Here's the output from the CLI using the --verbose flag:
>
> zev@zev-X58A-UD7:~$ spread --verbose wizard spread-test
> ==========================
>  Starting capturing process
>  ==========================
> Workflow: Initializing workflow spread-test
> bagit: Adding path /home/zev/spread-test/bag-info.txt to payload
> bagit: Adding path spread-test/config.yml to payload
> spreads.plugin: Finding devices for driver "CHDKCameraDevice"
> Found 2 devices!
> Setting up devices for capturing.
> Workflow: Preparing capture.
> Workflow: Preparing capture in devices
> spreads encountered an error:
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line 321, in main
>     run()
>   File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line 308, in run
>     args.subcommand(config)
>   File "/usr/local/lib/python2.7/dist-packages/spreads/cli.py", line 388, in wizard
>     capture(config)
>   File "/usr/local/lib/python2.7/dist-packages/spreads/cli.py", line 335, in capture
>     workflow.prepare_capture()
>   File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 880, in prepare_capture
>     util.check_futures_exceptions(futures)
>   File "/usr/local/lib/python2.7/dist-packages/spreads/util.py", line 119, in check_futures_exceptions
>     raise next(x for x in futures if x.exception()).exception()
> AttributeError: 'str' object has no attribute 'msg'
>
> Please let me know if there's anything else I can provide.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DIYBookScanner/spreads/issues/188#issuecomment-98614251>
> .
>



-- 
Mark Van den Borre
Hogestraat 16
3000 Leuven, België
+32 486 961726

**Comment by jbaiter** [comment]
@markvdb, probably a good idea, I'll see what I can do.

@Zev-Chonoles: I think the error is due to an error condition in the PTP communication with the device. Unfortunately my error-parser in the `chdkptp.py` library seems to have been a bit too naive, which is why you're seeing a rather unhelpful error message.

I just updated the `chdkptp.py` code to improve on that, could you please upgrade your installed version?

To do so, just run this (depending on your setup, you might have to prepend a `sudo`):
```
$ pip install http://jbaiter.de/files/chdkptp.py-0.1.4beta.tar.gz
```

**Comment by Zev-Chonoles** [comment]
@jbaiter Thanks for looking into this - it isn't working yet, but the error message changed to `AttributeError: 'str' object has no attribute 'get'`. Here's the full output:

```
zev@zev-X58A-UD7:~$ sudo pip install http://jbaiter.de/files/chdkptp.py-0.1.4beta.tar.gz
[sudo] password for zev:
Downloading/unpacking http://jbaiter.de/files/chdkptp.py-0.1.4beta.tar.gz
  Downloading chdkptp.py-0.1.4beta.tar.gz (263kB): 263kB downloaded
  Running setup.py (path:/tmp/pip-ix4sK7-build/setup.py) egg_info for package from http://jbaiter.de/files/chdkptp.py-0.1.4beta.tar.gz

Requirement already satisfied (use --upgrade to upgrade): lupa>=1.1 in /usr/local/lib/python2.7/dist-packages (from chdkptp.py==0.1.4beta)
Installing collected packages: chdkptp.py
  Found existing installation: chdkptp.py 0.1.3
    Uninstalling chdkptp.py:
      Successfully uninstalled chdkptp.py
  Running setup.py install for chdkptp.py
    patching file Makefile
    patching file chdkptp.c
    patching file include.mk
    make: Entering directory `/tmp/pip-ix4sK7-build/chdkptp/vendor/chdkptp'
    make[1]: Entering directory `/tmp/pip-ix4sK7-build/chdkptp/vendor/chdkptp/lfs'
    gcc -MMD -DCHDKPTP_OSTYPE=\"Linux\" -Wall -fPIC -g -DLUA_COMPAT_ALL=1 -g -I/usr/include/lua5.2 -c -o lfs.o lfs.c
    make[1]: Leaving directory `/tmp/pip-ix4sK7-build/chdkptp/vendor/chdkptp/lfs'
    gcc -MMD -DCHDKPTP_OSTYPE=\"Linux\" -Wall -fPIC -g -DLUA_COMPAT_ALL=1 -g -DCHDKPTP_READLINE -I/usr/include/lua5.2 -I./chdk_headers -DCHDKPTP_BUILD_NUM=0 -DCHDKPTP_REL_DESC="\"alpha\"" -c -o properties.o properties.c
    gcc -MMD -DCHDKPTP_OSTYPE=\"Linux\" -Wall -fPIC -g -DLUA_COMPAT_ALL=1 -g -DCHDKPTP_READLINE -I/usr/include/lua5.2 -I./chdk_headers -DCHDKPTP_BUILD_NUM=0 -DCHDKPTP_REL_DESC="\"alpha\"" -c -o ptp.o ptp.c
    gcc -MMD -DCHDKPTP_OSTYPE=\"Linux\" -Wall -fPIC -g -DLUA_COMPAT_ALL=1 -g -DCHDKPTP_READLINE -I/usr/include/lua5.2 -I./chdk_headers -DCHDKPTP_BUILD_NUM=0 -DCHDKPTP_REL_DESC="\"alpha\"" -c -o chdkptp.o chdkptp.c
    chdkptp.c:2082:12: warning: ‘gui_inited’ defined but not used [-Wunused-variable]
     static int gui_inited;
                ^
    gcc -MMD -DCHDKPTP_OSTYPE=\"Linux\" -Wall -fPIC -g -DLUA_COMPAT_ALL=1 -g -DCHDKPTP_READLINE -I/usr/include/lua5.2 -I./chdk_headers -DCHDKPTP_BUILD_NUM=0 -DCHDKPTP_REL_DESC="\"alpha\"" -c -o lbuf.o lbuf.c
    gcc -MMD -DCHDKPTP_OSTYPE=\"Linux\" -Wall -fPIC -g -DLUA_COMPAT_ALL=1 -g -DCHDKPTP_READLINE -I/usr/include/lua5.2 -I./chdk_headers -DCHDKPTP_BUILD_NUM=0 -DCHDKPTP_REL_DESC="\"alpha\"" -c -o liveimg.o liveimg.c
    gcc -MMD -DCHDKPTP_OSTYPE=\"Linux\" -Wall -fPIC -g -DLUA_COMPAT_ALL=1 -g -DCHDKPTP_READLINE -I/usr/include/lua5.2 -I./chdk_headers -DCHDKPTP_BUILD_NUM=0 -DCHDKPTP_REL_DESC="\"alpha\"" -c -o rawimg.o rawimg.c
    gcc -MMD -DCHDKPTP_OSTYPE=\"Linux\" -Wall -fPIC -g -DLUA_COMPAT_ALL=1 -g -DCHDKPTP_READLINE -I/usr/include/lua5.2 -I./chdk_headers -DCHDKPTP_BUILD_NUM=0 -DCHDKPTP_REL_DESC="\"alpha\"" -c -o luautil.o luautil.c
    gcc -o chdkptp lfs/lfs.o properties.o ptp.o chdkptp.o lbuf.o liveimg.o rawimg.o luautil.o  -g  -llua5.2 -lusb -lm -ldl -lreadline -lhistory
    gcc -shared -o chdkptp.so lfs/lfs.o properties.o ptp.o chdkptp.o lbuf.o liveimg.o rawimg.o luautil.o  -g  -llua5.2 -lusb -lm -ldl -lreadline -lhistory
    make: Leaving directory `/tmp/pip-ix4sK7-build/chdkptp/vendor/chdkptp'

Successfully installed chdkptp.py
Cleaning up...

zev@zev-X58A-UD7:~$ spread --verbose wizard spread-test                         
==========================
 Starting capturing process
 ==========================
Workflow: Initializing workflow spread-test
bagit: Adding path /home/zev/spread-test/bag-info.txt to payload
bagit: Adding path spread-test/config.yml to payload
spreads.plugin: Finding devices for driver "CHDKCameraDevice"
Found 2 devices!
Setting up devices for capturing.
Workflow: Preparing capture.
Workflow: Preparing capture in devices
spreads encountered an error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line 321, in main
    run()
  File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line 308, in run
    args.subcommand(config)
  File "/usr/local/lib/python2.7/dist-packages/spreads/cli.py", line 388, in wizard
    capture(config)
  File "/usr/local/lib/python2.7/dist-packages/spreads/cli.py", line 335, in capture
    workflow.prepare_capture()
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 880, in prepare_capture
    util.check_futures_exceptions(futures)
  File "/usr/local/lib/python2.7/dist-packages/spreads/util.py", line 119, in check_futures_exceptions
    raise next(x for x in futures if x.exception()).exception()
AttributeError: 'str' object has no attribute 'get'
```

**Comment by adongy** [comment]
Can you update your spreads version? The plugins look borked...

**Comment by Zev-Chonoles** [comment]
@adongy I updated the spreads installation but it didn't seem to help (output below), should I try updating the dependencies also?

```
zev@zev-X58A-UD7:~$ sudo pip install http://buildbot.diybookscanner.org/nightly/spreads-latest.tar.gz
[sudo] password for zev:
Downloading/unpacking http://buildbot.diybookscanner.org/nightly/spreads-latest.tar.gz
  Downloading spreads-latest.tar.gz (1.6MB): 1.6MB downloaded
  Running setup.py (path:/tmp/pip-VszLgS-build/setup.py) egg_info for package from http://buildbot.diybookscanner.org/nightly/spreads-latest.tar.gz

Requirement already satisfied (use --upgrade to upgrade): colorama>=0.2.4 in /usr/lib/python2.7/dist-packages (from spreads==0.5git20150501.fe74)
Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.10 in /usr/local/lib/python2.7/dist-packages (from spreads==0.5git20150501.fe74)
Requirement already satisfied (use --upgrade to upgrade): futures>=2.1 in /usr/local/lib/python2.7/dist-packages (from spreads==0.5git20150501.fe74)
Requirement already satisfied (use --upgrade to upgrade): blinker>=1.3 in /usr/local/lib/python2.7/dist-packages (from spreads==0.5git20150501.fe74)
Requirement already satisfied (use --upgrade to upgrade): roman>=2.0.0 in /usr/local/lib/python2.7/dist-packages (from spreads==0.5git20150501.fe74)
Requirement already satisfied (use --upgrade to upgrade): psutil>=2.0.0 in /usr/local/lib/python2.7/dist-packages (from spreads==0.5git20150501.fe74)
Requirement already satisfied (use --upgrade to upgrade): isbnlib>=3.3.8 in /usr/local/lib/python2.7/dist-packages (from spreads==0.5git20150501.fe74)
Requirement already satisfied (use --upgrade to upgrade): enum34>=1.0.3 in /usr/local/lib/python2.7/dist-packages (from spreads==0.5git20150501.fe74)
Requirement already satisfied (use --upgrade to upgrade): pathlib>=1.0.1 in /usr/local/lib/python2.7/dist-packages (from spreads==0.5git20150501.fe74)
Installing collected packages: spreads
  Found existing installation: spreads 0.5git20150426.f8de
    Uninstalling spreads:
      Successfully uninstalled spreads
  Running setup.py install for spreads

    Installing spread script to /usr/local/bin
Successfully installed spreads
Cleaning up...

zev@zev-X58A-UD7:~$ spread --verbose wizard spread-test                         
==========================
 Starting capturing process
 ==========================
Workflow: Initializing workflow spread-test
bagit: Adding path /home/zev/spread-test/bag-info.txt to payload
bagit: Adding path spread-test/config.yml to payload
spreads.plugin: Finding devices for driver "CHDKCameraDevice"
Found 2 devices!
Setting up devices for capturing.
Workflow: Preparing capture.
Workflow: Preparing capture in devices
spreads encountered an error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line 321, in main
    run()
  File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line 308, in run
    args.subcommand(config)
  File "/usr/local/lib/python2.7/dist-packages/spreads/cli.py", line 388, in wizard
    capture(config)
  File "/usr/local/lib/python2.7/dist-packages/spreads/cli.py", line 335, in capture
    workflow.prepare_capture()
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 883, in prepare_capture
    util.check_futures_exceptions(futures)
  File "/usr/local/lib/python2.7/dist-packages/spreads/util.py", line 119, in check_futures_exceptions
    raise next(x for x in futures if x.exception()).exception()
AttributeError: 'str' object has no attribute 'get'
```

**Comment by adongy** [comment]
Can you paste your config.yml ?

**Comment by Zev-Chonoles** [comment]
Here it is:

```
plugins: [autorotate, scantailor, gui]
scantailor:
    autopilot: no
    auto_margins: no
    rotate: yes
    content: no
    split_pages: yes
    deskew: yes
    detection: page
    margins:
    - 2.5
    - 2.5
    - 2.5
    - 2.5
device:
    upside_down: no
    flip_target_pages: no
    shoot_raw: no
    monochrome: no
    parallel_capture: yes
    focus_mode: autofocus_all
    dpi: 400
    whitebalance: Auto
    shutter_speed: 1/25
    zoom_level: 3
    sensitivity: 80
    focus_distance: 0
```

**Comment by adongy** [comment]
I feel like there should be more indents for the margins... Can you remove the margins block and retry ?

**Comment by Zev-Chonoles** [comment]
Not sure if I understood your suggestion, but I changed `config.yml` to

```
plugins: [autorotate, scantailor, gui]
scantailor:
    autopilot: no
    auto_margins: no
    rotate: yes
    content: no
    split_pages: yes
    deskew: yes
    detection: page
device:
    upside_down: no
    flip_target_pages: no
    shoot_raw: no
    monochrome: no
    parallel_capture: yes
    focus_mode: autofocus_all
    dpi: 400
    whitebalance: Auto
    shutter_speed: 1/25
    zoom_level: 3
    sensitivity: 80
    focus_distance: 0
```

It leads to the same output:

```
zev@zev-X58A-UD7:~$ spread --verbose wizard spread-test
==========================
 Starting capturing process
 ==========================
Workflow: Initializing workflow spread-test
bagit: Adding path /home/zev/spread-test/bag-info.txt to payload
bagit: Adding path spread-test/config.yml to payload
spreads.plugin: Finding devices for driver "CHDKCameraDevice"
Found 2 devices!
Setting up devices for capturing.
Workflow: Preparing capture.
Workflow: Preparing capture in devices
spreads encountered an error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line 321, in main
    run()
  File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line 308, in run
    args.subcommand(config)
  File "/usr/local/lib/python2.7/dist-packages/spreads/cli.py", line 388, in wizard
    capture(config)
  File "/usr/local/lib/python2.7/dist-packages/spreads/cli.py", line 335, in capture
    workflow.prepare_capture()
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 883, in prepare_capture
    util.check_futures_exceptions(futures)
  File "/usr/local/lib/python2.7/dist-packages/spreads/util.py", line 119, in check_futures_exceptions
    raise next(x for x in futures if x.exception()).exception()
AttributeError: 'str' object has no attribute 'get'
```

**Comment by markvdb** [comment]
Zev,

You may also want to drop by irc.freenode.net #diybookscanner .

2015-05-10 19:17 GMT+02:00 Zev Chonoles <notifications@github.com>:

> Not sure if I understood your suggestion, but I changed config.yml to
>
> plugins: [autorotate, scantailor, gui]
> scantailor:
>     autopilot: no
>     auto_margins: no
>     rotate: yes
>     content: no
>     split_pages: yes
>     deskew: yes
>     detection: page
> device:
>     upside_down: no
>     flip_target_pages: no
>     shoot_raw: no
>     monochrome: no
>     parallel_capture: yes
>     focus_mode: autofocus_all
>     dpi: 400
>     whitebalance: Auto
>     shutter_speed: 1/25
>     zoom_level: 3
>     sensitivity: 80
>     focus_distance: 0
>
> It leads to the same output:
>
> zev@zev-X58A-UD7:~$ spread --verbose wizard spread-test
> ==========================
>  Starting capturing process
>  ==========================
> Workflow: Initializing workflow spread-test
> bagit: Adding path /home/zev/spread-test/bag-info.txt to payload
> bagit: Adding path spread-test/config.yml to payload
> spreads.plugin: Finding devices for driver "CHDKCameraDevice"
> Found 2 devices!
> Setting up devices for capturing.
> Workflow: Preparing capture.
> Workflow: Preparing capture in devices
> spreads encountered an error:
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line 321, in main
>     run()
>   File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line 308, in run
>     args.subcommand(config)
>   File "/usr/local/lib/python2.7/dist-packages/spreads/cli.py", line 388, in wizard
>     capture(config)
>   File "/usr/local/lib/python2.7/dist-packages/spreads/cli.py", line 335, in capture
>     workflow.prepare_capture()
>   File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 883, in prepare_capture
>     util.check_futures_exceptions(futures)
>   File "/usr/local/lib/python2.7/dist-packages/spreads/util.py", line 119, in check_futures_exceptions
>     raise next(x for x in futures if x.exception()).exception()
> AttributeError: 'str' object has no attribute 'get'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DIYBookScanner/spreads/issues/188#issuecomment-100670861>
> .
>



-- 
Mark Van den Borre
Hogestraat 16
3000 Leuven, België
+32 486 961726

**Comment by adongy** [comment]
Small update from IRC: issue comes from the camera not being able to switch to record mode.

**Comment by jbaiter** [comment]
I assume it was the gphoto vfs service that was sitting on the USB device again? We should probably check for that in the chdkcamera plugin, this happens far too often :-/
As for the weird error, I found out that I had a bad instantiation of the `PTPError` exception in the chdkptp.py library, this has been fixed now, the error should be more explicit the next time it occurs .)
https://github.com/jbaiter/chdkptp.py/commit/250b10cfbeb0052d7404e6901234f8f863f8c3b2

**Comment by meelash** [comment]
Hi, any chance we could get more info about how to address the issue? I seem to be having something similar, and while the clues about it being related to the camera already being in use by gphoto are useful, I'm not really sure how to go forward fixing it.
