### ISSUE TITLE
Tornado throws: [Errno 13] Permission denied 

### ISSUE THREAD

**Issue by boredland** [DIYBookScanner/spreads#196]
The posprocessor isn't discoverable from the spreadpi, entering the IP in spreadpi config changes nothing. Both devices throw an error.

``` The debug from the processor ```
```
spreadsplug.web: Starting scanning station server in "processor" mode
huey.consumer.ConsumerThread: 1 worker threads
huey.consumer.ConsumerThread: Setting signal handler
huey.consumer.ConsumerThread: Huey consumer initialized with following commands
+ process_workflow
+ upload_workflow
+ transfer_to_stick
+ output_workflow
huey.consumer.ConsumerThread: Starting scheduler thread
huey.consumer.ConsumerThread: Starting worker threads
huey.consumer.ConsumerThread: Starting periodic task scheduler thread
spreadsplug.web.discovery: Starting discovery listener
spreads encountered an error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line 321, in main
    run()
  File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line 308, in run
    args.subcommand(config)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/app.py", line 169, in run
    app.run_server()
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/app.py", line 375, in run_server
    self.application.listen(self._listening_port)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1788, in listen
    server.listen(port, address)
  File "/usr/local/lib/python2.7/dist-packages/tornado/tcpserver.py", line 126, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/local/lib/python2.7/dist-packages/tornado/netutil.py", line 187, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 13] Permission denied
```

``` The Debug from spreadpi ```
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", line 327, in view_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", line 429, in discover_postprocessors
    return jsonify(servers=["{0}:{1}".format(*addr) for addr in servers])
IndexError: tuple index out of range
```

**Comment by adongy** [comment]
The server doesn't have permission to listen, can you try a free, high port? (over 2048 iirc)

**Comment by boredland** [comment]
So dont I have to change the port 5000 to 2060 (for example) on both, spreadpi and processor?

**Comment by adongy** [comment]
Yes

**Comment by boredland** [comment]
Thanks alot!

**Comment by adongy** [comment]
So did it work? If so, you can close the issue.
