### ISSUE TITLE
AttributeError: 'Configuration' object has no attribute 'set',

### ISSUE THREAD

**Issue by boredland** [DIYBookScanner/spreads#198]
I get the following when pushing scans from raspberry to processor:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spreads/vendor/huey/consumer.py", line 149, in process_task
    self.huey.execute(task)
  File "/usr/local/lib/python2.7/dist-packages/spreads/vendor/huey/api.py", line 236, in execute
    result = task.execute()
  File "/usr/local/lib/python2.7/dist-packages/spreads/vendor/huey/api.py", line 415, in execute
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/tasks.py", line 107, in upload_workflow
    tmp_cfg.set(user_config)
AttributeError: 'Configuration' object has no attribute 'set'
```

**Comment by adongy** [comment]
This is a real bug, config has no set attribute, I guess it was meant to be an dict() update-like mechanism.

I /think/ user_config is a Configuration object (didn't really check), so replace tmp_cfg.set(user_config) by
```
for k, v in user_config.iteritems():
    tmp_cfg[k] = v
```

And it should continue.

**Comment by boredland** [comment]
Closing this myself as the reporter — I'm no longer pursuing it, and I'd rather not leave it sitting in your triage queue.

No action is needed from the maintainers, and this says nothing about the validity of the report: if anyone else is hitting the same thing, please reopen or file fresh.

**Comment by boredland** [comment]
Reopening — please disregard my previous comment.

That closure was a mistake on my side: it came from a bulk sweep of my own filed issues, not from a considered decision to withdraw this report. Sorry for the noise in your notifications.

The report stands as originally written.
