### ISSUE TITLE
Error using ScanTailor rotation for processing

### ISSUE THREAD

**Issue by boredland** [DIYBookScanner/spreads#199]
without things are fine.

```
huey.consumer.ConsumerThread: Unhandled exception in worker thread
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spreads/vendor/huey/consumer.py", line 149, in process_task
    self.huey.execute(task)
  File "/usr/local/lib/python2.7/dist-packages/spreads/vendor/huey/api.py", line 236, in execute
    result = task.execute()
  File "/usr/local/lib/python2.7/dist-packages/spreads/vendor/huey/api.py", line 415, in execute
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/tasks.py", line 166, in process_workflow
    workflow.process()
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 972, in process
    self._run_hook('process', self.pages, processed_path)
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 833, in _run_hook
    getattr(plug, hook_name)(*args)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/scantailor.py", line 284, in process
    projectfile, out_dir)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/scantailor.py", line 112, in _generate_configuration
    marginconf = self.config['margins'].as_str_seq()
  File "/usr/local/lib/python2.7/dist-packages/spreads/vendor/confit.py", line 398, in as_str_seq
    'a list'.format(self.name)
ConfigTypeError: scantailor.margins must be a whitespace-separated string or a list
```

**Comment by adongy** [comment]
You have to define the margins (even if it's 0) in your spread config

**Comment by boredland** [comment]
Thanks alot! We should add those margins to the config by default.

**Comment by boredland** [comment]
Closing this myself as the reporter — I'm no longer pursuing it, and I'd rather not leave it sitting in your triage queue.

No action is needed from the maintainers, and this says nothing about the validity of the report: if anyone else is hitting the same thing, please reopen or file fresh.

**Comment by boredland** [comment]
Reopening — please disregard my previous comment.

That closure was a mistake on my side: it came from a bulk sweep of my own filed issues, not from a considered decision to withdraw this report. Sorry for the noise in your notifications.

The report stands as originally written.
