### ISSUE TITLE
CalledProcessError: Command '[u'djvubind', u'/tmp/tmpROZiyr', u'--no-ocr']' returned non-zero exit status 1,

### ISSUE THREAD

**Issue by boredland** [DIYBookScanner/spreads#201]
Hi there,

I ran the `djvubind /tmp/tmpROZiyr --no-ocr` trying to reproduce that, but in fact it worked without a problem...

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spreads/vendor/huey/consumer.py", line 149, in process_task
    self.huey.execute(task)
  File "/usr/local/lib/python2.7/dist-packages/spreads/vendor/huey/api.py", line 236, in execute
    result = task.execute()
  File "/usr/local/lib/python2.7/dist-packages/spreads/vendor/huey/api.py", line 415, in execute
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/tasks.py", line 174, in output_workflow
    workflow.output()
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 985, in output
    self.table_of_contents)
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 833, in _run_hook
    getattr(plug, hook_name)(*args)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/djvubind.py", line 74, in output
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '[u'djvubind', u'/tmp/tmpROZiyr', u'--no-ocr']' returned non-zero exit status 1

```

**Comment by boredland** [comment]
Closing this myself as the reporter — I'm no longer pursuing it, and I'd rather not leave it sitting in your triage queue.

No action is needed from the maintainers, and this says nothing about the validity of the report: if anyone else is hitting the same thing, please reopen or file fresh.

**Comment by boredland** [comment]
Reopening — please disregard my previous comment.

That closure was a mistake on my side: it came from a bulk sweep of my own filed issues, not from a considered decision to withdraw this report. Sorry for the noise in your notifications.

The report stands as originally written.
