### ISSUE TITLE
InvalidExifData: Invalid start of EXIF data,

### ISSUE THREAD

**Issue by mcdonaldm** [DIYBookScanner/spreads#202]
Hi,

I just started testing my new scanner today. My first workflow didn't have any problems. But now when I try to scan I get these errors when I try to capture my first images.

I've done a clean boot of the pi, started spreads and access via a browser on a connected PC on the network.

I'm using 2 Canon A2500 cameras.

Thanks
Michael

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", line 327, in view_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", line 951, in trigger_capture
    workflow.capture(retake=('retake' in request.args))
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 104, in wrapped_func
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 928, in capture
    util.check_futures_exceptions(futures)
  File "/usr/local/lib/python2.7/dist-packages/spreads/util.py", line 119, in check_futures_exceptions
    raise next(x for x in futures if x.exception()).exception()
InvalidExifData: Invalid start of EXIF data

```

**Comment by mcdonaldm** [comment]
before this I had pulled the plug on the pi while spreads was running. I just saw in a previous post that doing that is definitely a no no. Is it possible I need to re-load the spreads img file to my Pi 2?

**Comment by markvdb** [comment]
Yes, do that.

M

2015-07-04 21:12 GMT+03:00 mcdonaldm <notifications@github.com>:

> before this I had pulled the plug on the pi while spreads was running. I
> just saw in a previous post that doing that is definitely a no no. Is it
> possible I need to re-load the spreads img file to my Pi 2?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DIYBookScanner/spreads/issues/202#issuecomment-118539438>
> .
>



-- 
Mark Van den Borre
Hogestraat 16
3000 Leuven, België
+32 486 961726

**Comment by mcdonaldm** [comment]
That did the trick. I guess something got corrupted.

Thanks
