### ISSUE TITLE
NoExifDataFound: Could not find EXIF data,

### ISSUE THREAD

**Issue by mcdonaldm** [DIYBookScanner/spreads#203]
I'm running on a Raspberry Pi 2. I get this error out of the blue. I was capturing images and then I receive this error.

I had received it a few days ago and thought I had corrupted my installation. So I did re-install of spreadpi from the Archivist-1.img file. I captured about 150 images and now receive this message.

Thanks
Michael

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", line 327, in view_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", line 951, in trigger_capture
    workflow.capture(retake=('retake' in request.args))
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 104, in wrapped_func
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 928, in capture
    util.check_futures_exceptions(futures)
  File "/usr/local/lib/python2.7/dist-packages/spreads/util.py", line 119, in check_futures_exceptions
    raise next(x for x in futures if x.exception()).exception()
NoExifDataFound: Could not find EXIF data

```

**Comment by mcdonaldm** [comment]
After a normal shutdown and reboot I tried capturing again but now receive the error "Invalid start of EXIF data.

Any ideas of why this continues to happen?

Thanks
Michael

**Comment by duerig** [comment]
This seems to sometimes happen in a way that corrupts a workflow. Switching to a new workflow can fix things. It also just happens in a completely transient way sometimes where one attempted scan has he issue, but retaking the scan works just fine.
