### ISSUE TITLE
TypeError: 'NoneType' object is not callable,

### ISSUE THREAD

**Issue by datamads** [DIYBookScanner/spreads#207]
I keep getting this. And when it does, it stops the capture process. Not really sure what causes it. Anyone else have this? Best regards

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", line 327, in view_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", line 929, in prepare_capture
    workflow.prepare_capture()
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 883, in prepare_capture
    util.check_futures_exceptions(futures)
  File "/usr/local/lib/python2.7/dist-packages/spreads/util.py", line 119, in check_futures_exceptions
    raise next(x for x in futures if x.exception()).exception()
TypeError: 'NoneType' object is not callable

```

**Comment by datamads** [comment]
Oh and it's on Duerigs image+Version 0.5git20150611.c802 of spreads

**Comment by datamads** [comment]
This might have something to do with the zoom setting. When I set it to 20, this error occurs, but when I set it 12 it seems to stop.
