### ISSUE TITLE
LuaError

### ISSUE THREAD

**Issue by datamads** [DIYBookScanner/spreads#209]
Hey guys. 

This error continuously happens to me on the CLI version. Any help on what to do? 
´´´
spreads encountered an error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line 321, in main
    run()
  File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line 308, in run
    args.subcommand(config)
  File "/usr/local/lib/python2.7/dist-packages/spreads/cli.py", line 388, in wizard
    capture(config)
  File "/usr/local/lib/python2.7/dist-packages/spreads/cli.py", line 340, in capture
    _trigger_loop()
  File "/usr/local/lib/python2.7/dist-packages/spreads/cli.py", line 314, in _trigger_loop
    workflow.capture(retake=(char == 'r'))
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 104, in wrapped_func
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 928, in capture
    util.check_futures_exceptions(futures)
  File "/usr/local/lib/python2.7/dist-packages/spreads/util.py", line 119, in check_futures_exceptions
    raise next(x for x in futures if x.exception()).exception()
LuaError: {'etype': 'connect_no_dev', 'msg': 'no matching device', 'traceback': '\nstack traceback:\n\t[C]: in function \'connect\'\n\t...on2.7/dist-packages/chdkptp/vendor/chdkptp/lua/chdku.lua:1510: in function \'connect\'\n\t...on2.7/dist-packages/chdkptp/vendor/chdkptp/lua/chdku.lua:1537: in function <...on2.7/dist-packages/chdkptp/vendor/chdkptp/lua/chdku.lua:1525>\n\t[C]: in function \'pcall\'\n\t[string "<python>"]:1: in function <[string "<python>"]:1>'}
´´´

**Comment by adongy** [comment]
No matching device: did you properly connect the camera? Can you connect to it with chdkptp cli?

On August 3, 2015 5:29:02 PM CEST, Mads Kjeldgaard <notifications@github.com> wrote:
>Hey guys. 
>
>This error continuously happens to me on the CLI version. Any help on
>what to do? 
>´´´
>spreads encountered an error:
>Traceback (most recent call last):
>File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line
>321, in main
>    run()
>File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line
>308, in run
>    args.subcommand(config)
>File "/usr/local/lib/python2.7/dist-packages/spreads/cli.py", line 388,
>in wizard
>    capture(config)
>File "/usr/local/lib/python2.7/dist-packages/spreads/cli.py", line 340,
>in capture
>    _trigger_loop()
>File "/usr/local/lib/python2.7/dist-packages/spreads/cli.py", line 314,
>in _trigger_loop
>    workflow.capture(retake=(char == 'r'))
>File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line
>104, in wrapped_func
>    func(*args, **kwargs)
>File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line
>928, in capture
>    util.check_futures_exceptions(futures)
>File "/usr/local/lib/python2.7/dist-packages/spreads/util.py", line
>119, in check_futures_exceptions
>    raise next(x for x in futures if x.exception()).exception()
>LuaError: {'etype': 'connect_no_dev', 'msg': 'no matching device',
>'traceback': '\nstack traceback:\n\t[C]: in function
>\'connect\'\n\t...on2.7/dist-packages/chdkptp/vendor/chdkptp/lua/chdku.lua:1510:
>in function
>\'connect\'\n\t...on2.7/dist-packages/chdkptp/vendor/chdkptp/lua/chdku.lua:1537:
>in function
><...on2.7/dist-packages/chdkptp/vendor/chdkptp/lua/chdku.lua:1525>\n\t[C]:
>in function \'pcall\'\n\t[string "<python>"]:1: in function <[string
>"<python>"]:1>'}
>´´´
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/DIYBookScanner/spreads/issues/209

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by datamads** [comment]
I tried the following chdkptp command and it seemed to stop the abovementioned error, now I just get the NoneType-error
```
___> connect
open_camera_dev_usb: ptp_opensession failed 0x2ff
open_camera_dev_usb:usb_ptp_device_reset(): Device or resource busy
usb_ptp_get_device_status(): Device or resource busy
connected: Canon PowerShot A1400, max packet size 512
```

**Comment by adongy** [comment]
Are you on ubuntu? If so try to kill gphoto before running the connect command

On August 4, 2015 3:16:50 PM CEST, Mads Kjeldgaard <notifications@github.com> wrote:
>I tried the following chdkptp command and it seemed to stop the
>abovementioned error, now I just get the NoneType-error
>```
>___> connect
>open_camera_dev_usb: ptp_opensession failed 0x2ff
>open_camera_dev_usb:usb_ptp_device_reset(): Device or resource busy
>usb_ptp_get_device_status(): Device or resource busy
>connected: Canon PowerShot A1400, max packet size 512
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/DIYBookScanner/spreads/issues/209#issuecomment-127604154

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
