### ISSUE TITLE
Exception thrown/camera crash during configure

### ISSUE THREAD

**Issue by gareth8118** [DIYBookScanner/spreads#216]
Resurrecting my cardboard box single camera setup and have run into this:

```
Do you want to setup the focus for your cameras? [y/N]: y
Please turn on one of your capture devices.
Press any key to continue
Please put a book with as little whitespace as possible under your cameras.
Press any button to continue
spreads encountered an error:
Traceback (most recent call last):
  File "/home/gareth/projects/bookscanner/spreads/spreads/main.py", line 321, in main
    run()
  File "/home/gareth/projects/bookscanner/spreads/spreads/main.py", line 308, in run
    args.subcommand(config)
  File "/home/gareth/projects/bookscanner/spreads/spreads/cli.py", line 246, in configure
    focus = devs[0]._acquire_focus()
  File "/home/gareth/projects/bookscanner/spreads/spreadsplug/dev/chdkcamera.py", line 314, in _acquire_focus
    self._device.lua_execute("press('shoot_half')")
  File "/home/gareth/projects/bookscanner/spreadsenv/local/lib/python2.7/site-packages/chdkptp/device.py", line 186, in lua_execute
    """ % (lua_code, remote_libs)).values()
  File "/home/gareth/projects/bookscanner/spreadsenv/local/lib/python2.7/site-packages/chdkptp/lua.py", line 70, in pexecute
    return self._parse_rval(self._rt.execute(checked_code))
  File "/home/gareth/projects/bookscanner/spreadsenv/local/lib/python2.7/site-packages/chdkptp/lua.py", line 36, in _parse_rval
    self._raise_exception(rval[2])
IndexError: tuple index out of range
```
The camera is crashing at the same time so I suspect there is a chdkptp problem at the root of this, but I can't tell from the error what it is failing on.

**Comment by adongy** [comment]
try to run '! press('shoot_half'). you can even do it in the chdkptp gui.

**Comment by gareth8118** [comment]
I don't have a GUI build of chdkptp, just the command line version.

```
con> rec
con 1> ! press('shoot_half')
ERROR: call failed:[string "press('shoot_half')"]:1: attempt to call global 'press' (a nil value)
stack traceback:
	[C]: in function 'xpcall'
	/opt/chdkptp/lua/cli.lua:654: in function </opt/chdkptp/lua/cli.lua:649>
	(...tail calls...)
	[C]: in function 'xpcall'
	/opt/chdkptp/lua/cli.lua:244: in function 'execute'
	/opt/chdkptp/lua/cli.lua:351: in function </opt/chdkptp/lua/cli.lua:342>
	(...tail calls...)
	/opt/chdkptp/lua/main.lua:281: in main chunk
	[C]: in function 'require'
	[string "require('main')"]:1: in main chunk
```
No camera crash on this test though.

**Comment by gareth8118** [comment]
Think I've solve it - although udev had been told to ignore this camera in the rules, gphoto was still attempting to mount it at insertion time and it was putting it into a bad state. Removing the executable bit from the volume monitor thus:
```
sudo chmod -x /usr/lib/gvfs/gvfs-gphoto2-volume-monitor
```
has stopped the crash in the web interface.
