### ISSUE TITLE
getting error after running "spread gui" and web is not working 

### ISSUE THREAD

**Issue by saqiibiqbal** [DIYBookScanner/spreads#219]
hello all,

i am using spreads on ubuntu 14.04 after following this tutorial:
https://github.com/OliPelz/spreads-ubuntu-trusty

every thing else is working fine now except for:
when i run spread gui, after giving the folder path and click on capture, it returns an error:

QImage: :scalewidth: image is null image
QImage: :scalewidth: image is null image
File:/"path"/python2.7/site-packages/spreadplug/gui/gui.py , line 417, in doPostprocess 
Raise future.exception()
OSError: [error 2] no such file or directory: ‘/"path"/image.jpg’

and the spread web is also not working. 

Thanks.

**Comment by saqiibiqbal** [comment]
Any body?

**Comment by atomotic** [comment]
follow the **getting started** in the README for installation instruction:
https://github.com/DIYBookScanner/spreads/blob/master/README.rst#getting-started

and use only **spread web**, the gui has not been updated lately.

**Comment by saqiibiqbal** [comment]
i followed the instructions, and getting this error now on a newly installed ubuntu 14.04 with spreads etc.
spreadsplug.web: Thumbnail is not in JPEG format.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full                                                                                        _dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in disp                                                                                        atch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", li                                                                                        ne 732, in view_func
    return func(*args, page=page, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", li                                                                                        ne 764, in view_func
    return func(fpath, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", li                                                                                        ne 867, in get_page_image_thumb
    thumbnail = get_thumbnail(fpath)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/util.py", line 20                                                                                        6, in get_thumbnail
    thumb = img.exif_thumbnail
  File "/usr/local/lib/python2.7/dist-packages/jpegtran/transform.py", line 46,                                                                                         in exif_thumbnail
    return JPEGImage(blob=lib.Exif(self.data).thumbnail)
  File "/usr/local/lib/python2.7/dist-packages/jpegtran/lib.py", line 272, in th                                                                                        umbnail
    raise ValueError("Thumbnail is not in JPEG format.")
ValueError: Thumbnail is not in JPEG format.
tornado.access: 500 GET /api/workflow/26869f68-68df-4b1d-91e2-eddc840c6382/page/                                                                                        0/raw/thumb (192.168.3.175) 50.29ms
spreadsplug.web: Thumbnail is not in JPEG format.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full                                                                                        _dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in disp                                                                                        atch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", li                                                                                        ne 732, in view_func
    return func(*args, page=page, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", li                                                                                        ne 764, in view_func
    return func(fpath, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", li                                                                                        ne 867, in get_page_image_thumb
    thumbnail = get_thumbnail(fpath)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/util.py", line 20                                                                                        6, in get_thumbnail
    thumb = img.exif_thumbnail
  File "/usr/local/lib/python2.7/dist-packages/jpegtran/transform.py", line 46,                                                                                         in exif_thumbnail
    return JPEGImage(blob=lib.Exif(self.data).thumbnail)
  File "/usr/local/lib/python2.7/dist-packages/jpegtran/lib.py", line 272, in th                                                                                        umbnail
    raise ValueError("Thumbnail is not in JPEG format.")
ValueError: Thumbnail is not in JPEG format.
tornado.access: 500 GET /api/workflow/26869f68-68df-4b1d-91e2-eddc840c6382/page/                                                                                        0/raw/thumb (192.168.3.175) 44.08ms
spreadsplug.web: Thumbnail is not in JPEG format.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full                                                                                        _dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in disp                                                                                        atch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", li                                                                                        ne 732, in view_func
    return func(*args, page=page, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", li                                                                                        ne 764, in view_func
    return func(fpath, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", li                                                                                        ne 867, in get_page_image_thumb
    thumbnail = get_thumbnail(fpath)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/util.py", line 20                                                                                        6, in get_thumbnail
    thumb = img.exif_thumbnail
  File "/usr/local/lib/python2.7/dist-packages/jpegtran/transform.py", line 46,                                                                                         in exif_thumbnail
    return JPEGImage(blob=lib.Exif(self.data).thumbnail)
  File "/usr/local/lib/python2.7/dist-packages/jpegtran/lib.py", line 272, in th                                                                                        umbnail
    raise ValueError("Thumbnail is not in JPEG format.")
ValueError: Thumbnail is not in JPEG format.
tornado.access: 500 GET /api/workflow/26869f68-68df-4b1d-91e2-eddc840c6382/page/                                                                                        0/raw/thumb

**Comment by jbaiter** [comment]
Can you upload some sample images? Looks like the extraction of the thumbnail from the EXIF data is failing. What cameras are you using?

**Comment by saqiibiqbal** [comment]
i don't have any sample's yet as it is not showing any sort of image, only thumbnails with no data.
i am using cannon powershot sx170IS.

**Comment by jbaiter** [comment]
But there should be images in the project directory, have you checked there?

**Comment by saqiibiqbal** [comment]
i have resolved that issue now i can see images on the web but when i try to crop an image it shows me the same thumbnail. 
i don't understand why. can you please tell me the path to the file that invoked during this process so that i can look into it.
i tried to find the file but unable to do so. 
it isnt showing any exceptions/errors after running spread web in debugging mode. 

Thanks for all the help.

**Comment by jbaiter** [comment]
If you did not change the default settings, there should be a directory in `~/scans` (that is, the scans directory in your home directory) with your project name. Look under `data/raw`.
For you cropping issues, take a look at your browser's developer console (`Ctrl+Shift+j` in Chrome, `F12` in Firefox) and see if there are any error messages.

**Comment by saqiibiqbal** [comment]
hi jbaiter,
whats happening is that i can now see the image on the web but when i try to open the image from the folder it still say image is corrupted or no data found. 
so the error mentioned above disappeared but it is still storing the image as null, that's why we are seeing the image as thumbnail during cropping. i have attached the image: 
![000](https://cloud.githubusercontent.com/assets/17546917/13490951/3ee66f56-e151-11e5-9ae1-e95915248ae2.jpg)

**Comment by jbaiter** [comment]
- Which driver are you using? chdk or gphoto2?
- If you're using CHDK, what's your firmware version?
- What you're saying is that you can see the image in the web interface, but when you crop it the image gets 'destroyed'?

**Comment by saqiibiqbal** [comment]
- i am using chdk
- version: 1.4.1
- after creating the workflow and then i take pictures by clicking on the camera button i can see the images on top of the camera button with other options etc. and then when i try to crop the image it just shows me the thumbnail.

and now i have followed this link to install spreads on ubuntu 14.04
https://github.com/DIYBookScanner/spreads/blob/master/README.rst#getting-started

Thanks.

**Comment by nafraf** [comment]
Which Image Size are you using to capture? What does happen if you use a lower resolution?
