### ISSUE TITLE
travis build fails with failure in test_submit_workflow

### ISSUE THREAD

**Issue by jayvdb** [DIYBookScanner/spreads#222]
```
=================================== FAILURES ===================================
_____________________________ test_submit_workflow _____________________________
requests = <MagicMock name='requests' id='140594900806480'>
app = <Flask 'spreadsplug.web'>
tmpdir = local('/tmp/pytest-of-travis/pytest-0/test_submit_workflow0')
    @mock.patch('spreadsplug.web.tasks.requests')
    def test_submit_workflow(requests, app, tmpdir):
        app.config['postproc_server'] = 'http://127.0.0.1:5000'
        app.config['mode'] = 'scanner'
        client = app.test_client()
        wfid = create_workflow(client)
        with mock.patch('spreadsplug.web.app.task_queue') as mock_tq:
            mock_tq.task.return_value = lambda x: x
            requests.post.return_value.json.return_value = {'id': 1}
            client.post('/api/workflow/{0}/submit'.format(wfid),
                        content_type="application/json",
                        data=json.dumps({'config': {'plugins': []},
                                         'server': '127.0.0.1:5000'}))
>       assert requests.post.call_count == 1
E       assert 0 == 1
E        +  where 0 = <MagicMock name='requests.post' id='140594918952912'>.call_count
E        +    where <MagicMock name='requests.post' id='140594918952912'> = <MagicMock name='requests' id='140594900806480'>.post
tests/web_test.py:186: AssertionError
----------------------------- Captured stderr call -----------------------------
spreadsplug.web: too many values to unpack
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/travis/build/jayvdb/spreads/spreadsplug/web/endpoints.py", line 327, in view_func
    return func(*args, **kwargs)
  File "/home/travis/build/jayvdb/spreads/spreadsplug/web/endpoints.py", line 686, in submit_workflow
    start_output=data.get('start_output', False))
  File "/home/travis/build/jayvdb/spreads/spreadsplug/web/tasks.py", line 115, in upload_workflow
    zsize = calculate_zipsize(zstream.paths_to_write)
  File "/home/travis/build/jayvdb/spreads/spreadsplug/web/util.py", line 256, in calculate_zipsize
    for args, kwargs in frecords:
ValueError: too many values to unpack
```
https://travis-ci.org/jayvdb/spreads/jobs/120802725

**Comment by jbaiter** [comment]
Yay, a nice case of bitrot :-) Turns out the zipstream package saw a new release that changed the API. I updated `setup.py` to pin the version to the previous release, the test should pass now.
