### ISSUE TITLE
Can not configure spreads

### ISSUE THREAD

**Issue by Hildepont** [DIYBookScanner/spreads#232]
hello,
first time with spreads,
I installed it following the documentation
I installed chdk on the SD cards with STICK (both for canon A2500 on 4gb cards)
I try to configure spread :

```
spreadhild@debian:~$` spread configure
Please select a device driver from the following list:
  [0]: Keep current (chdkcamera)
  [1]: gphoto2camera
  [2]: chdkcamera
  [3]: dummy
  [4]: None
Select a driver: 2    
Selected "chdkcamera" as device driver
Please select your desired plugins from the following list:
    1: autorotate
    2: djvubind
    3: gui
    4: hidtrigger
    5: intervaltrigger
    6: pdfbeads
    7: scantailor
    8: tesseract
    9: web
Select a plugin (or hit enter to finish): 
Do you want to configure the target_page of your devices?
(Required for shooting with two devices) [y/N]: y
Setting target page on cameras
Please connect and turn on the device labeled 'odd'
Press any key when ready.
open_camera_dev_usb: ptp_opensession failed 0x2ff
open_camera_dev_usb:usb_ptp_device_reset(): Device or resource busy
usb_ptp_get_device_status(): Device or resource busy
Configured 'odd' device.
Please turn off the device.
Press any key when ready.
Please connect and turn on the device labeled 'even'
Press any key when ready.
open_camera_dev_usb: ptp_opensession failed 0x2ff
open_camera_dev_usb:usb_ptp_device_reset(): Device or resource busy
usb_ptp_get_device_status(): Device or resource busy
attempted to close non-present device 002:005
Configured 'even' device.
Please turn off the device.
Press any key when ready.
Do you want to setup the focus for your cameras? [y/N]: y
Please turn on one of your capture devices.
Press any key to continue
open_camera_dev_usb: ptp_opensession failed 0x2ff
open_camera_dev_usb:usb_ptp_device_reset(): Device or resource busy
usb_ptp_get_device_status(): Device or resource busy
attempted to close non-present device 002:006
Please put a book with as little whitespace as possible under your cameras.
Press any button to continue
spreads encountered an error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line 321, in main
    run()
  File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line 308, in run
    args.subcommand(config)
  File "/usr/local/lib/python2.7/dist-packages/spreads/cli.py", line 246, in configure
    focus = devs[0]._acquire_focus()
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/dev/chdkcamera.py", line 311, in _acquire_focus
    self._device.switch_mode('record')
  File "/usr/local/lib/python2.7/dist-packages/chdkptp/device.py", line 111, in switch_mode
    raise PTPError('Could not switch mode')
  File "/usr/local/lib/python2.7/dist-packages/chdkptp/lua.py", line 15, in __init__
    .format(err_table.msg, err_table.ptp_rc)))
AttributeError: 'str' object has no attribute 'msg'

hild@debian:~$
```

As you can see, it doesn't work :(
Can someone tell me where the problem is ?

**Comment by atomotic** [comment]
`open_camera_dev_usb:usb_ptp_device_reset(): Device or resource busy`

check if there is something that prevents connection to usb cameras, maybe in your window manager there is a running kde/gnome photo or whatever.
