### ISSUE TITLE
error running spread output

### ISSUE THREAD

**Issue by whohoho** [DIYBookScanner/spreads#235]
spread --version
spreads 0.5git20190701.5075

$ which djvubind
/usr/bin/djvubind

spreads encountered an error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line 321, in main
    run()
  File "/usr/local/lib/python2.7/dist-packages/spreads/main.py", line 308, in run
    args.subcommand(config)
  File "/usr/local/lib/python2.7/dist-packages/spreads/cli.py", line 376, in output
    workflow.output()
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 988, in output
    self.table_of_contents)
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 833, in _run_hook
    getattr(plug, hook_name)(*args)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/djvubind.py", line 75, in output
    os.rename("book.djvu", unicode(djvu_file))
OSError: [Errno 2] No such file or directory

**Comment by markvdb** [comment]
I read this as a problem with finding a file rather than a dependency problem..

Sorry I won't be able to help with this myself. I'll keep the bug open since this is definitely something someone might want to solve eventually.

In the mean time, do also feel free to look at older revisions...
