### ISSUE TITLE
error when setting raw capture mode

### ISSUE THREAD

**Issue by whohoho** [DIYBookScanner/spreads#236]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/spreads-0.5git20190701.5075-py2.7.egg/spreadsplug/intervaltrigger.py", line 78, in _trigger_loop
    capture_func()
  File "/usr/local/lib/python2.7/dist-packages/spreads-0.5git20190701.5075-py2.7.egg/spreads/workflow.py", line 104, in wrapped_func
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/spreads-0.5git20190701.5075-py2.7.egg/spreads/workflow.py", line 931, in capture
    util.check_futures_exceptions(futures)
  File "/usr/local/lib/python2.7/dist-packages/spreads-0.5git20190701.5075-py2.7.egg/spreads/util.py", line 119, in check_futures_exceptions
    raise next(x for x in futures if x.exception()).exception()
InvalidExifData: Invalid start of EXIF data

**Comment by markvdb** [comment]
Sorry, can't really help you with this.

Leaving for future reference in case someone feels like fixing.
